// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

import '../types/channel.dart';
import '../types/channel_type.dart';

class ChannelTableHandle {
  final TableCache<Channel> _cache;

  ChannelTableHandle(this._cache);

  /// Creates a [ChannelTableHandle] backed by a [TableCache]
  /// configured for the "channel" table.
  static TableCache<Channel> createCache() {
    return TableCache<Channel>(
      tableName: 'channel',
      decoder: Channel.readBsatn,
      pkExtractor: (row) => row.id,
    );
  }

  /// All currently cached rows.
  Iterable<Channel> get rows => _cache.rows;

  /// The number of cached rows.
  int get count => _cache.count;

  /// Finds a row by its primary key [id].
  Channel? findById(int id) =>
      _cache.findByPk(id);

  /// Returns all rows matching the given [test] predicate.
  Iterable<Channel> where(bool Function(Channel) test) =>
      _cache.where(test);

  /// Registers a callback invoked when a row is inserted.
  void onInsert(void Function(Channel) callback) =>
      _cache.onInsert(callback);

  /// Registers a callback invoked when a row is updated.
  void onUpdate(void Function(Channel, Channel) callback) =>
      _cache.onUpdate(callback);

  /// Registers a callback invoked when a row is deleted.
  void onDelete(void Function(Channel) callback) =>
      _cache.onDelete(callback);

  /// Removes a previously registered insert callback.
  void removeOnInsert(void Function(Channel) callback) =>
      _cache.removeOnInsert(callback);

  /// Removes a previously registered update callback.
  void removeOnUpdate(void Function(Channel, Channel) callback) =>
      _cache.removeOnUpdate(callback);

  /// Removes a previously registered delete callback.
  void removeOnDelete(void Function(Channel) callback) =>
      _cache.removeOnDelete(callback);
}
