// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

import '../types/direct_message.dart';

class DirectMessageTableHandle {
  final TableCache<DirectMessage> _cache;

  DirectMessageTableHandle(this._cache);

  /// Creates a [DirectMessageTableHandle] backed by a [TableCache]
  /// configured for the "direct_message" table.
  static TableCache<DirectMessage> createCache() {
    return TableCache<DirectMessage>(
      tableName: 'direct_message',
      decoder: DirectMessage.readBsatn,
      pkExtractor: (row) => row.id,
    );
  }

  /// All currently cached rows.
  Iterable<DirectMessage> get rows => _cache.rows;

  /// The number of cached rows.
  int get count => _cache.count;

  /// Finds a row by its primary key [id].
  DirectMessage? findById(int id) =>
      _cache.findByPk(id);

  /// Returns all rows matching the given [test] predicate.
  Iterable<DirectMessage> where(bool Function(DirectMessage) test) =>
      _cache.where(test);

  /// Registers a callback invoked when a row is inserted.
  void onInsert(void Function(DirectMessage) callback) =>
      _cache.onInsert(callback);

  /// Registers a callback invoked when a row is updated.
  void onUpdate(void Function(DirectMessage, DirectMessage) callback) =>
      _cache.onUpdate(callback);

  /// Registers a callback invoked when a row is deleted.
  void onDelete(void Function(DirectMessage) callback) =>
      _cache.onDelete(callback);

  /// Removes a previously registered insert callback.
  void removeOnInsert(void Function(DirectMessage) callback) =>
      _cache.removeOnInsert(callback);

  /// Removes a previously registered update callback.
  void removeOnUpdate(void Function(DirectMessage, DirectMessage) callback) =>
      _cache.removeOnUpdate(callback);

  /// Removes a previously registered delete callback.
  void removeOnDelete(void Function(DirectMessage) callback) =>
      _cache.removeOnDelete(callback);
}
