// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

import '../types/message.dart';

class MessageTableHandle {
  final TableCache<Message> _cache;

  MessageTableHandle(this._cache);

  /// Creates a [MessageTableHandle] backed by a [TableCache]
  /// configured for the "message" table.
  static TableCache<Message> createCache() {
    return TableCache<Message>(
      tableName: 'message',
      decoder: Message.readBsatn,
      pkExtractor: (row) => row.id,
    );
  }

  /// All currently cached rows.
  Iterable<Message> get rows => _cache.rows;

  /// The number of cached rows.
  int get count => _cache.count;

  /// Finds a row by its primary key [id].
  Message? findById(int id) =>
      _cache.findByPk(id);

  /// Returns all rows matching the given [test] predicate.
  Iterable<Message> where(bool Function(Message) test) =>
      _cache.where(test);

  /// Registers a callback invoked when a row is inserted.
  void onInsert(void Function(Message) callback) =>
      _cache.onInsert(callback);

  /// Registers a callback invoked when a row is updated.
  void onUpdate(void Function(Message, Message) callback) =>
      _cache.onUpdate(callback);

  /// Registers a callback invoked when a row is deleted.
  void onDelete(void Function(Message) callback) =>
      _cache.onDelete(callback);

  /// Removes a previously registered insert callback.
  void removeOnInsert(void Function(Message) callback) =>
      _cache.removeOnInsert(callback);

  /// Removes a previously registered update callback.
  void removeOnUpdate(void Function(Message, Message) callback) =>
      _cache.removeOnUpdate(callback);

  /// Removes a previously registered delete callback.
  void removeOnDelete(void Function(Message) callback) =>
      _cache.removeOnDelete(callback);
}
