// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

import '../types/server_member.dart';

class ServerMemberTableHandle {
  final TableCache<ServerMember> _cache;

  ServerMemberTableHandle(this._cache);

  /// Creates a [ServerMemberTableHandle] backed by a [TableCache]
  /// configured for the "server_member" table.
  static TableCache<ServerMember> createCache() {
    return TableCache<ServerMember>(
      tableName: 'server_member',
      decoder: ServerMember.readBsatn,
      pkExtractor: (row) => row.id,
    );
  }

  /// All currently cached rows.
  Iterable<ServerMember> get rows => _cache.rows;

  /// The number of cached rows.
  int get count => _cache.count;

  /// Finds a row by its primary key [id].
  ServerMember? findById(int id) =>
      _cache.findByPk(id);

  /// Returns all rows matching the given [test] predicate.
  Iterable<ServerMember> where(bool Function(ServerMember) test) =>
      _cache.where(test);

  /// Registers a callback invoked when a row is inserted.
  void onInsert(void Function(ServerMember) callback) =>
      _cache.onInsert(callback);

  /// Registers a callback invoked when a row is updated.
  void onUpdate(void Function(ServerMember, ServerMember) callback) =>
      _cache.onUpdate(callback);

  /// Registers a callback invoked when a row is deleted.
  void onDelete(void Function(ServerMember) callback) =>
      _cache.onDelete(callback);

  /// Removes a previously registered insert callback.
  void removeOnInsert(void Function(ServerMember) callback) =>
      _cache.removeOnInsert(callback);

  /// Removes a previously registered update callback.
  void removeOnUpdate(void Function(ServerMember, ServerMember) callback) =>
      _cache.removeOnUpdate(callback);

  /// Removes a previously registered delete callback.
  void removeOnDelete(void Function(ServerMember) callback) =>
      _cache.removeOnDelete(callback);
}
