// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

import '../types/user_roles.dart';

class UserRolesTableHandle {
  final TableCache<UserRoles> _cache;

  UserRolesTableHandle(this._cache);

  /// Creates a [UserRolesTableHandle] backed by a [TableCache]
  /// configured for the "user_roles" table.
  static TableCache<UserRoles> createCache() {
    return TableCache<UserRoles>(
      tableName: 'user_roles',
      decoder: UserRoles.readBsatn,
      pkExtractor: (row) => row.identity,
    );
  }

  /// All currently cached rows.
  Iterable<UserRoles> get rows => _cache.rows;

  /// The number of cached rows.
  int get count => _cache.count;

  /// Finds a row by its primary key [identity].
  UserRoles? findByIdentity(Identity identity) =>
      _cache.findByPk(identity);

  /// Returns all rows matching the given [test] predicate.
  Iterable<UserRoles> where(bool Function(UserRoles) test) =>
      _cache.where(test);

  /// Registers a callback invoked when a row is inserted.
  void onInsert(void Function(UserRoles) callback) =>
      _cache.onInsert(callback);

  /// Registers a callback invoked when a row is updated.
  void onUpdate(void Function(UserRoles, UserRoles) callback) =>
      _cache.onUpdate(callback);

  /// Registers a callback invoked when a row is deleted.
  void onDelete(void Function(UserRoles) callback) =>
      _cache.onDelete(callback);

  /// Removes a previously registered insert callback.
  void removeOnInsert(void Function(UserRoles) callback) =>
      _cache.removeOnInsert(callback);

  /// Removes a previously registered update callback.
  void removeOnUpdate(void Function(UserRoles, UserRoles) callback) =>
      _cache.removeOnUpdate(callback);

  /// Removes a previously registered delete callback.
  void removeOnDelete(void Function(UserRoles) callback) =>
      _cache.removeOnDelete(callback);
}
