// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

import '../types/user.dart';

class UserTableHandle {
  final TableCache<User> _cache;

  UserTableHandle(this._cache);

  /// Creates a [UserTableHandle] backed by a [TableCache]
  /// configured for the "user" table.
  static TableCache<User> createCache() {
    return TableCache<User>(
      tableName: 'user',
      decoder: User.readBsatn,
      pkExtractor: (row) => row.identity,
    );
  }

  /// All currently cached rows.
  Iterable<User> get rows => _cache.rows;

  /// The number of cached rows.
  int get count => _cache.count;

  /// Finds a row by its primary key [identity].
  User? findByIdentity(Identity identity) =>
      _cache.findByPk(identity);

  /// Returns all rows matching the given [test] predicate.
  Iterable<User> where(bool Function(User) test) =>
      _cache.where(test);

  /// Registers a callback invoked when a row is inserted.
  void onInsert(void Function(User) callback) =>
      _cache.onInsert(callback);

  /// Registers a callback invoked when a row is updated.
  void onUpdate(void Function(User, User) callback) =>
      _cache.onUpdate(callback);

  /// Registers a callback invoked when a row is deleted.
  void onDelete(void Function(User) callback) =>
      _cache.onDelete(callback);

  /// Removes a previously registered insert callback.
  void removeOnInsert(void Function(User) callback) =>
      _cache.removeOnInsert(callback);

  /// Removes a previously registered update callback.
  void removeOnUpdate(void Function(User, User) callback) =>
      _cache.removeOnUpdate(callback);

  /// Removes a previously registered delete callback.
  void removeOnDelete(void Function(User) callback) =>
      _cache.removeOnDelete(callback);
}
