// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

import '../types/user_settings.dart';

class UserSettingsTableHandle {
  final TableCache<UserSettings> _cache;

  UserSettingsTableHandle(this._cache);

  /// Creates a [UserSettingsTableHandle] backed by a [TableCache]
  /// configured for the "user_settings" table.
  static TableCache<UserSettings> createCache() {
    return TableCache<UserSettings>(
      tableName: 'user_settings',
      decoder: UserSettings.readBsatn,
      pkExtractor: (row) => row.id,
    );
  }

  /// All currently cached rows.
  Iterable<UserSettings> get rows => _cache.rows;

  /// The number of cached rows.
  int get count => _cache.count;

  /// Finds a row by its primary key [id].
  UserSettings? findById(int id) =>
      _cache.findByPk(id);

  /// Returns all rows matching the given [test] predicate.
  Iterable<UserSettings> where(bool Function(UserSettings) test) =>
      _cache.where(test);

  /// Registers a callback invoked when a row is inserted.
  void onInsert(void Function(UserSettings) callback) =>
      _cache.onInsert(callback);

  /// Registers a callback invoked when a row is updated.
  void onUpdate(void Function(UserSettings, UserSettings) callback) =>
      _cache.onUpdate(callback);

  /// Registers a callback invoked when a row is deleted.
  void onDelete(void Function(UserSettings) callback) =>
      _cache.onDelete(callback);

  /// Removes a previously registered insert callback.
  void removeOnInsert(void Function(UserSettings) callback) =>
      _cache.removeOnInsert(callback);

  /// Removes a previously registered update callback.
  void removeOnUpdate(void Function(UserSettings, UserSettings) callback) =>
      _cache.removeOnUpdate(callback);

  /// Removes a previously registered delete callback.
  void removeOnDelete(void Function(UserSettings) callback) =>
      _cache.removeOnDelete(callback);
}
