// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

import '../types/voice_state.dart';

class VoiceStateTableHandle {
  final TableCache<VoiceState> _cache;

  VoiceStateTableHandle(this._cache);

  /// Creates a [VoiceStateTableHandle] backed by a [TableCache]
  /// configured for the "voice_state" table.
  static TableCache<VoiceState> createCache() {
    return TableCache<VoiceState>(
      tableName: 'voice_state',
      decoder: VoiceState.readBsatn,
      pkExtractor: (row) => row.id,
    );
  }

  /// All currently cached rows.
  Iterable<VoiceState> get rows => _cache.rows;

  /// The number of cached rows.
  int get count => _cache.count;

  /// Finds a row by its primary key [id].
  VoiceState? findById(int id) =>
      _cache.findByPk(id);

  /// Returns all rows matching the given [test] predicate.
  Iterable<VoiceState> where(bool Function(VoiceState) test) =>
      _cache.where(test);

  /// Registers a callback invoked when a row is inserted.
  void onInsert(void Function(VoiceState) callback) =>
      _cache.onInsert(callback);

  /// Registers a callback invoked when a row is updated.
  void onUpdate(void Function(VoiceState, VoiceState) callback) =>
      _cache.onUpdate(callback);

  /// Registers a callback invoked when a row is deleted.
  void onDelete(void Function(VoiceState) callback) =>
      _cache.onDelete(callback);

  /// Removes a previously registered insert callback.
  void removeOnInsert(void Function(VoiceState) callback) =>
      _cache.removeOnInsert(callback);

  /// Removes a previously registered update callback.
  void removeOnUpdate(void Function(VoiceState, VoiceState) callback) =>
      _cache.removeOnUpdate(callback);

  /// Removes a previously registered delete callback.
  void removeOnDelete(void Function(VoiceState) callback) =>
      _cache.removeOnDelete(callback);
}
