// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'dart:typed_data';

import 'package:spacetimedb_sdk/spacetimedb.dart';

import 'types/channel_type.dart';

/// Callback type for reducer completion events.
typedef ReducerCallback = void Function(ReducerCallbackEvent event);

/// Provides typed methods for calling reducers and
/// registering callbacks for reducer completion events.
class RemoteReducers {
  final Future<void> Function(String reducer, Uint8List args) _callReducer;
  final void Function(String reducer, ReducerCallback callback) _onReducer;

  RemoteReducers({
    required Future<void> Function(String reducer, Uint8List args) callReducer,
    required void Function(String reducer, ReducerCallback callback) onReducer,
  })  : _callReducer = callReducer,
        _onReducer = onReducer;

  /// Calls the `create_channel` reducer.
  Future<void> createChannel(int serverId, String name, ChannelType channelType, String topic) {
    final encoder = BsatnEncoder();
    encoder.writeU64(serverId);
    encoder.writeString(name);
    channelType.writeBsatn(encoder);
    encoder.writeString(topic);
    return _callReducer('create_channel', encoder.toBytes());
  }

  /// Registers a callback for when `create_channel` completes.
  void onCreateChannel(ReducerCallback callback) {
    _onReducer('create_channel', callback);
  }

  /// Calls the `create_server` reducer.
  Future<void> createServer(String name, String iconUrl) {
    final encoder = BsatnEncoder();
    encoder.writeString(name);
    encoder.writeString(iconUrl);
    return _callReducer('create_server', encoder.toBytes());
  }

  /// Registers a callback for when `create_server` completes.
  void onCreateServer(ReducerCallback callback) {
    _onReducer('create_server', callback);
  }

  /// Calls the `delete_channel` reducer.
  Future<void> deleteChannel(int channelId) {
    final encoder = BsatnEncoder();
    encoder.writeU64(channelId);
    return _callReducer('delete_channel', encoder.toBytes());
  }

  /// Registers a callback for when `delete_channel` completes.
  void onDeleteChannel(ReducerCallback callback) {
    _onReducer('delete_channel', callback);
  }

  /// Calls the `delete_message` reducer.
  Future<void> deleteMessage(int messageId) {
    final encoder = BsatnEncoder();
    encoder.writeU64(messageId);
    return _callReducer('delete_message', encoder.toBytes());
  }

  /// Registers a callback for when `delete_message` completes.
  void onDeleteMessage(ReducerCallback callback) {
    _onReducer('delete_message', callback);
  }

  /// Calls the `delete_server` reducer.
  Future<void> deleteServer(int serverId) {
    final encoder = BsatnEncoder();
    encoder.writeU64(serverId);
    return _callReducer('delete_server', encoder.toBytes());
  }

  /// Registers a callback for when `delete_server` completes.
  void onDeleteServer(ReducerCallback callback) {
    _onReducer('delete_server', callback);
  }

  /// Calls the `edit_message` reducer.
  Future<void> editMessage(int messageId, String content) {
    final encoder = BsatnEncoder();
    encoder.writeU64(messageId);
    encoder.writeString(content);
    return _callReducer('edit_message', encoder.toBytes());
  }

  /// Registers a callback for when `edit_message` completes.
  void onEditMessage(ReducerCallback callback) {
    _onReducer('edit_message', callback);
  }

  /// Calls the `join_server` reducer.
  Future<void> joinServer(int serverId) {
    final encoder = BsatnEncoder();
    encoder.writeU64(serverId);
    return _callReducer('join_server', encoder.toBytes());
  }

  /// Registers a callback for when `join_server` completes.
  void onJoinServer(ReducerCallback callback) {
    _onReducer('join_server', callback);
  }

  /// Calls the `join_voice_channel` reducer.
  Future<void> joinVoiceChannel(int channelId) {
    final encoder = BsatnEncoder();
    encoder.writeU64(channelId);
    return _callReducer('join_voice_channel', encoder.toBytes());
  }

  /// Registers a callback for when `join_voice_channel` completes.
  void onJoinVoiceChannel(ReducerCallback callback) {
    _onReducer('join_voice_channel', callback);
  }

  /// Calls the `leave_server` reducer.
  Future<void> leaveServer(int serverId) {
    final encoder = BsatnEncoder();
    encoder.writeU64(serverId);
    return _callReducer('leave_server', encoder.toBytes());
  }

  /// Registers a callback for when `leave_server` completes.
  void onLeaveServer(ReducerCallback callback) {
    _onReducer('leave_server', callback);
  }

  /// Calls the `leave_voice_channel` reducer.
  Future<void> leaveVoiceChannel() {
    final encoder = BsatnEncoder();
    return _callReducer('leave_voice_channel', encoder.toBytes());
  }

  /// Registers a callback for when `leave_voice_channel` completes.
  void onLeaveVoiceChannel(ReducerCallback callback) {
    _onReducer('leave_voice_channel', callback);
  }

  /// Calls the `send_direct_message` reducer.
  Future<void> sendDirectMessage(Identity receiver, String content) {
    final encoder = BsatnEncoder();
    receiver.writeBsatn(encoder);
    encoder.writeString(content);
    return _callReducer('send_direct_message', encoder.toBytes());
  }

  /// Registers a callback for when `send_direct_message` completes.
  void onSendDirectMessage(ReducerCallback callback) {
    _onReducer('send_direct_message', callback);
  }

  /// Calls the `send_message` reducer.
  Future<void> sendMessage(int channelId, String content) {
    final encoder = BsatnEncoder();
    encoder.writeU64(channelId);
    encoder.writeString(content);
    return _callReducer('send_message', encoder.toBytes());
  }

  /// Registers a callback for when `send_message` completes.
  void onSendMessage(ReducerCallback callback) {
    _onReducer('send_message', callback);
  }

  /// Calls the `set_roles` reducer.
  Future<void> setRoles(int serverId, List<String> roleNames, List<int> permissions) {
    final encoder = BsatnEncoder();
    encoder.writeU64(serverId);
    encoder.writeArrayHeader(roleNames.length);
    for (final item in roleNames) {
      encoder.writeString(item);
    }
    encoder.writeArrayHeader(permissions.length);
    for (final item in permissions) {
      encoder.writeU32(item);
    }
    return _callReducer('set_roles', encoder.toBytes());
  }

  /// Registers a callback for when `set_roles` completes.
  void onSetRoles(ReducerCallback callback) {
    _onReducer('set_roles', callback);
  }

  /// Calls the `set_username` reducer.
  Future<void> setUsername(String username) {
    final encoder = BsatnEncoder();
    encoder.writeString(username);
    return _callReducer('set_username', encoder.toBytes());
  }

  /// Registers a callback for when `set_username` completes.
  void onSetUsername(ReducerCallback callback) {
    _onReducer('set_username', callback);
  }

  /// Calls the `test_error` reducer.
  Future<void> testError() {
    final encoder = BsatnEncoder();
    return _callReducer('test_error', encoder.toBytes());
  }

  /// Registers a callback for when `test_error` completes.
  void onTestError(ReducerCallback callback) {
    _onReducer('test_error', callback);
  }

  /// Calls the `toggle_deafen` reducer.
  Future<void> toggleDeafen() {
    final encoder = BsatnEncoder();
    return _callReducer('toggle_deafen', encoder.toBytes());
  }

  /// Registers a callback for when `toggle_deafen` completes.
  void onToggleDeafen(ReducerCallback callback) {
    _onReducer('toggle_deafen', callback);
  }

  /// Calls the `toggle_mute` reducer.
  Future<void> toggleMute() {
    final encoder = BsatnEncoder();
    return _callReducer('toggle_mute', encoder.toBytes());
  }

  /// Registers a callback for when `toggle_mute` completes.
  void onToggleMute(ReducerCallback callback) {
    _onReducer('toggle_mute', callback);
  }

  /// Calls the `update_channel` reducer.
  Future<void> updateChannel(int channelId, String name, String topic) {
    final encoder = BsatnEncoder();
    encoder.writeU64(channelId);
    encoder.writeString(name);
    encoder.writeString(topic);
    return _callReducer('update_channel', encoder.toBytes());
  }

  /// Registers a callback for when `update_channel` completes.
  void onUpdateChannel(ReducerCallback callback) {
    _onReducer('update_channel', callback);
  }

  /// Calls the `update_profile` reducer.
  Future<void> updateProfile(String displayName, String avatarUrl, String statusText) {
    final encoder = BsatnEncoder();
    encoder.writeString(displayName);
    encoder.writeString(avatarUrl);
    encoder.writeString(statusText);
    return _callReducer('update_profile', encoder.toBytes());
  }

  /// Registers a callback for when `update_profile` completes.
  void onUpdateProfile(ReducerCallback callback) {
    _onReducer('update_profile', callback);
  }

  /// Calls the `update_server` reducer.
  Future<void> updateServer(int serverId, String name, String iconUrl) {
    final encoder = BsatnEncoder();
    encoder.writeU64(serverId);
    encoder.writeString(name);
    encoder.writeString(iconUrl);
    return _callReducer('update_server', encoder.toBytes());
  }

  /// Registers a callback for when `update_server` completes.
  void onUpdateServer(ReducerCallback callback) {
    _onReducer('update_server', callback);
  }

  /// Calls the `update_settings` reducer.
  Future<void> updateSettings(String? theme, String? language, bool notifications, String? emoji) {
    final encoder = BsatnEncoder();
    if (theme != null) {
      encoder.writeOptionSome();
      encoder.writeString(theme);
    } else {
      encoder.writeOptionNone();
    }
    if (language != null) {
      encoder.writeOptionSome();
      encoder.writeString(language);
    } else {
      encoder.writeOptionNone();
    }
    encoder.writeBool(notifications);
    if (emoji != null) {
      encoder.writeOptionSome();
      encoder.writeString(emoji);
    } else {
      encoder.writeOptionNone();
    }
    return _callReducer('update_settings', encoder.toBytes());
  }

  /// Registers a callback for when `update_settings` completes.
  void onUpdateSettings(ReducerCallback callback) {
    _onReducer('update_settings', callback);
  }

}
