// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

enum ChannelType {
  text(0),
  voice(1);

  final int tag;
  const ChannelType(this.tag);

  void writeBsatn(BsatnEncoder encoder) {
    encoder.writeSumTag(tag);
  }

  static ChannelType readBsatn(BsatnDecoder decoder) {
    final tag = decoder.readSumTag();
    return ChannelType.values.firstWhere(
      (v) => v.tag == tag,
      orElse: () => throw BsatnDecodeException('Unknown ChannelType tag: $tag'),
    );
  }
}
