// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

import 'channel_type.dart';

class Channel {
  final int id;
  final int serverId;
  final String name;
  final ChannelType channelType;
  final String topic;
  final int position;

  Channel({
    required this.id,
    required this.serverId,
    required this.name,
    required this.channelType,
    required this.topic,
    required this.position,
  });

  void writeBsatn(BsatnEncoder encoder) {
    encoder.writeU64(id);
    encoder.writeU64(serverId);
    encoder.writeString(name);
    channelType.writeBsatn(encoder);
    encoder.writeString(topic);
    encoder.writeU32(position);
  }

  static Channel readBsatn(BsatnDecoder decoder) {
    return Channel(
      id: decoder.readU64(),
      serverId: decoder.readU64(),
      name: decoder.readString(),
      channelType: ChannelType.readBsatn(decoder),
      topic: decoder.readString(),
      position: decoder.readU32(),
    );
  }

  @override
  bool operator ==(Object other) =>
      other is Channel && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'Channel(id: $id, serverId: $serverId, name: $name)';
}
