// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

class DirectMessage {
  final int id;
  final Identity sender;
  final Identity receiver;
  final String content;
  final Timestamp sentAt;

  DirectMessage({
    required this.id,
    required this.sender,
    required this.receiver,
    required this.content,
    required this.sentAt,
  });

  void writeBsatn(BsatnEncoder encoder) {
    encoder.writeU64(id);
    sender.writeBsatn(encoder);
    receiver.writeBsatn(encoder);
    encoder.writeString(content);
    sentAt.writeBsatn(encoder);
  }

  static DirectMessage readBsatn(BsatnDecoder decoder) {
    return DirectMessage(
      id: decoder.readU64(),
      sender: Identity.readBsatn(decoder),
      receiver: Identity.readBsatn(decoder),
      content: decoder.readString(),
      sentAt: Timestamp.readBsatn(decoder),
    );
  }

  @override
  bool operator ==(Object other) =>
      other is DirectMessage && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'DirectMessage(id: $id, sender: $sender, receiver: $receiver)';
}
