// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

class Message {
  final int id;
  final int channelId;
  final Identity sender;
  final String content;
  final Timestamp sentAt;
  final bool edited;

  Message({
    required this.id,
    required this.channelId,
    required this.sender,
    required this.content,
    required this.sentAt,
    required this.edited,
  });

  void writeBsatn(BsatnEncoder encoder) {
    encoder.writeU64(id);
    encoder.writeU64(channelId);
    sender.writeBsatn(encoder);
    encoder.writeString(content);
    sentAt.writeBsatn(encoder);
    encoder.writeBool(edited);
  }

  static Message readBsatn(BsatnDecoder decoder) {
    return Message(
      id: decoder.readU64(),
      channelId: decoder.readU64(),
      sender: Identity.readBsatn(decoder),
      content: decoder.readString(),
      sentAt: Timestamp.readBsatn(decoder),
      edited: decoder.readBool(),
    );
  }

  @override
  bool operator ==(Object other) =>
      other is Message && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'Message(id: $id, channelId: $channelId, sender: $sender)';
}
