// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

class Server {
  final int id;
  final String name;
  final Identity ownerIdentity;
  final String iconUrl;
  final Timestamp createdAt;

  Server({
    required this.id,
    required this.name,
    required this.ownerIdentity,
    required this.iconUrl,
    required this.createdAt,
  });

  void writeBsatn(BsatnEncoder encoder) {
    encoder.writeU64(id);
    encoder.writeString(name);
    ownerIdentity.writeBsatn(encoder);
    encoder.writeString(iconUrl);
    createdAt.writeBsatn(encoder);
  }

  static Server readBsatn(BsatnDecoder decoder) {
    return Server(
      id: decoder.readU64(),
      name: decoder.readString(),
      ownerIdentity: Identity.readBsatn(decoder),
      iconUrl: decoder.readString(),
      createdAt: Timestamp.readBsatn(decoder),
    );
  }

  @override
  bool operator ==(Object other) =>
      other is Server && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'Server(id: $id, name: $name, ownerIdentity: $ownerIdentity)';
}
