// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

class ServerMember {
  final int id;
  final int serverId;
  final Identity identity;
  final String role;
  final Timestamp joinedAt;

  ServerMember({
    required this.id,
    required this.serverId,
    required this.identity,
    required this.role,
    required this.joinedAt,
  });

  void writeBsatn(BsatnEncoder encoder) {
    encoder.writeU64(id);
    encoder.writeU64(serverId);
    identity.writeBsatn(encoder);
    encoder.writeString(role);
    joinedAt.writeBsatn(encoder);
  }

  static ServerMember readBsatn(BsatnDecoder decoder) {
    return ServerMember(
      id: decoder.readU64(),
      serverId: decoder.readU64(),
      identity: Identity.readBsatn(decoder),
      role: decoder.readString(),
      joinedAt: Timestamp.readBsatn(decoder),
    );
  }

  @override
  bool operator ==(Object other) =>
      other is ServerMember && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'ServerMember(id: $id, serverId: $serverId, identity: $identity)';
}
