// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

class UserSettings {
  final int id;
  final Identity ownerIdentity;
  final String? theme;
  final String? language;
  final bool notificationsEnabled;
  final String? customStatusEmoji;

  UserSettings({
    required this.id,
    required this.ownerIdentity,
    this.theme,
    this.language,
    required this.notificationsEnabled,
    this.customStatusEmoji,
  });

  void writeBsatn(BsatnEncoder encoder) {
    encoder.writeU64(id);
    ownerIdentity.writeBsatn(encoder);
    if (theme != null) {
      encoder.writeOptionSome();
      encoder.writeString(theme!);
    } else {
      encoder.writeOptionNone();
    }
    if (language != null) {
      encoder.writeOptionSome();
      encoder.writeString(language!);
    } else {
      encoder.writeOptionNone();
    }
    encoder.writeBool(notificationsEnabled);
    if (customStatusEmoji != null) {
      encoder.writeOptionSome();
      encoder.writeString(customStatusEmoji!);
    } else {
      encoder.writeOptionNone();
    }
  }

  static UserSettings readBsatn(BsatnDecoder decoder) {
    return UserSettings(
      id: decoder.readU64(),
      ownerIdentity: Identity.readBsatn(decoder),
      theme: decoder.readOption() ? decoder.readString() : null,
      language: decoder.readOption() ? decoder.readString() : null,
      notificationsEnabled: decoder.readBool(),
      customStatusEmoji: decoder.readOption() ? decoder.readString() : null,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is UserSettings && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'UserSettings(id: $id, ownerIdentity: $ownerIdentity, theme: $theme)';
}
