// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

class User {
  final Identity identity;
  final String username;
  final String displayName;
  final String avatarUrl;
  final bool online;
  final String statusText;

  User({
    required this.identity,
    required this.username,
    required this.displayName,
    required this.avatarUrl,
    required this.online,
    required this.statusText,
  });

  void writeBsatn(BsatnEncoder encoder) {
    identity.writeBsatn(encoder);
    encoder.writeString(username);
    encoder.writeString(displayName);
    encoder.writeString(avatarUrl);
    encoder.writeBool(online);
    encoder.writeString(statusText);
  }

  static User readBsatn(BsatnDecoder decoder) {
    return User(
      identity: Identity.readBsatn(decoder),
      username: decoder.readString(),
      displayName: decoder.readString(),
      avatarUrl: decoder.readString(),
      online: decoder.readBool(),
      statusText: decoder.readString(),
    );
  }

  @override
  bool operator ==(Object other) =>
      other is User && identity == other.identity;

  @override
  int get hashCode => identity.hashCode;

  @override
  String toString() => 'User(identity: $identity, username: $username, displayName: $displayName)';
}
