// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

class UserRoles {
  final Identity identity;
  final int serverId;
  final List<String> roleNames;
  final List<int> permissions;

  UserRoles({
    required this.identity,
    required this.serverId,
    required this.roleNames,
    required this.permissions,
  });

  void writeBsatn(BsatnEncoder encoder) {
    identity.writeBsatn(encoder);
    encoder.writeU64(serverId);
    encoder.writeArrayHeader(roleNames.length);
    for (final item in roleNames) {
      encoder.writeString(item);
    }
    encoder.writeArrayHeader(permissions.length);
    for (final item in permissions) {
      encoder.writeU32(item);
    }
  }

  static UserRoles readBsatn(BsatnDecoder decoder) {
    return UserRoles(
      identity: Identity.readBsatn(decoder),
      serverId: decoder.readU64(),
      roleNames: [for (var i = 0; i < decoder.readArrayHeader(); i++) decoder.readString()],
      permissions: [for (var i = 0; i < decoder.readArrayHeader(); i++) decoder.readU32()],
    );
  }

  @override
  bool operator ==(Object other) =>
      other is UserRoles && identity == other.identity;

  @override
  int get hashCode => identity.hashCode;

  @override
  String toString() => 'UserRoles(identity: $identity, serverId: $serverId, roleNames: $roleNames)';
}
