// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.
import 'package:spacetimedb_sdk/spacetimedb.dart';

class VoiceState {
  final int id;
  final int channelId;
  final Identity identity;
  final bool muted;
  final bool deafened;

  VoiceState({
    required this.id,
    required this.channelId,
    required this.identity,
    required this.muted,
    required this.deafened,
  });

  void writeBsatn(BsatnEncoder encoder) {
    encoder.writeU64(id);
    encoder.writeU64(channelId);
    identity.writeBsatn(encoder);
    encoder.writeBool(muted);
    encoder.writeBool(deafened);
  }

  static VoiceState readBsatn(BsatnDecoder decoder) {
    return VoiceState(
      id: decoder.readU64(),
      channelId: decoder.readU64(),
      identity: Identity.readBsatn(decoder),
      muted: decoder.readBool(),
      deafened: decoder.readBool(),
    );
  }

  @override
  bool operator ==(Object other) =>
      other is VoiceState && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'VoiceState(id: $id, channelId: $channelId, identity: $identity)';
}
