// Dart code generator for SpacetimeDB module schemas.
//
// Takes a parsed [ModuleSchema] and generates typed Dart source files for
// table types, table handles, reducers, and custom types (enums/structs).

import 'dart:io';

import 'package:meta/meta.dart';

import 'schema.dart';

/// Header comment prepended to every generated file.
const _generatedHeader =
    '// AUTO-GENERATED BY SPACETIMEDB DART SDK. DO NOT EDIT.';

/// Generates typed Dart code from a SpacetimeDB module schema.
class DartGenerator {
  final ModuleSchema schema;
  final String outputDir;

  /// Maps typespace index to the resolved name for that type.
  /// Populated during [_resolveTypeNames].
  final Map<int, String> _typeNames = {};

  /// Set of typespace indices that are used as table product types.
  final Set<int> _tableTypeRefs = {};

  /// Set of typespace indices that correspond to simple enums.
  final Set<int> _enumTypeRefs = {};

  /// Set of typespace indices that correspond to tagged unions (complex sums).
  final Set<int> _taggedUnionTypeRefs = {};

  /// Set of typespace indices that correspond to custom product types (structs)
  /// that are not table types and not special types.
  final Set<int> _customProductTypeRefs = {};

  DartGenerator({required this.schema, required this.outputDir});

  /// Generates all Dart files for the schema.
  Future<void> generate() async {
    _resolveTypeNames();

    final typesDir = Directory('$outputDir/types');
    final tablesDir = Directory('$outputDir/tables');
    final reducersDir = Directory(outputDir);

    await typesDir.create(recursive: true);
    await tablesDir.create(recursive: true);
    await reducersDir.create(recursive: true);

    // Generate type files for each table.
    for (final table in schema.tables) {
      final code = _generateTableTypeCode(table);
      final fileName = _toSnakeCase(table.name);
      await File('${typesDir.path}/$fileName.dart').writeAsString(code);
    }

    // Generate custom type files (enums and standalone structs).
    await _generateCustomTypeFiles(typesDir);

    // Generate table handle files.
    for (final table in schema.tables) {
      final code = _generateTableHandleCode(table);
      final fileName = _toSnakeCase(table.name);
      await File('${tablesDir.path}/${fileName}_table.dart')
          .writeAsString(code);
    }

    // Generate reducers file.
    final reducersCode = _generateReducersCode();
    await File('${reducersDir.path}/reducers.dart').writeAsString(reducersCode);

    // Generate barrel export.
    final barrelCode = _generateBarrelCode();
    await File('$outputDir/module.dart').writeAsString(barrelCode);
  }

  // ---------------------------------------------------------------------------
  // Type name resolution
  // ---------------------------------------------------------------------------

  /// Populates [_typeNames] and the various type-ref sets by examining all
  /// typespace entries and how they are referenced.
  void _resolveTypeNames() {
    // First pass: mark table type refs.
    for (final table in schema.tables) {
      _tableTypeRefs.add(table.productTypeRef);
      _typeNames[table.productTypeRef] = _toPascalCase(table.name);
    }

    // Second pass: scan all types in the typespace to find named custom types.
    // Walk all reducer params and table fields for RefType references.
    final referencedRefs = <int>{};
    _collectRefs(referencedRefs);

    // Third pass: name and classify every referenced typespace entry.
    for (var i = 0; i < schema.typespace.length; i++) {
      if (_typeNames.containsKey(i)) continue; // Already named (table type).

      final type = schema.typespace[i].type;
      if (type is SumType) {
        // Try to derive a name. We look for a reducer param or table field
        // that references this index.
        final name = _findNameForRef(i) ?? 'Type$i';
        _typeNames[i] = _toPascalCase(name);
        if (type.isSimpleEnum) {
          _enumTypeRefs.add(i);
        } else if (type is! OptionType) {
          _taggedUnionTypeRefs.add(i);
        }
      } else if (type is ProductType) {
        // Check if it is a special type.
        if (type is IdentityType ||
            type is ConnectionIdType ||
            type is TimestampType) {
          continue;
        }
        if (type.elements.isNotEmpty && !_tableTypeRefs.contains(i)) {
          final name = _findNameForRef(i) ?? 'Type$i';
          _typeNames[i] = _toPascalCase(name);
          _customProductTypeRefs.add(i);
        }
      }
    }
  }

  /// Collects all RefType index values found anywhere in the schema.
  void _collectRefs(Set<int> refs) {
    for (final table in schema.tables) {
      final type = schema.typespace[table.productTypeRef].type;
      _collectRefsFromType(type, refs);
    }
    for (final reducer in schema.reducers) {
      for (final param in reducer.params) {
        _collectRefsFromType(param.type, refs);
      }
    }
  }

  void _collectRefsFromType(AlgebraicType type, Set<int> refs) {
    switch (type) {
      case RefType():
        refs.add(type.ref);
        if (type.ref >= 0 && type.ref < schema.typespace.length) {
          _collectRefsFromType(schema.typespace[type.ref].type, refs);
        }
      case ArrayType():
        _collectRefsFromType(type.elementType, refs);
      case MapType():
        _collectRefsFromType(type.keyType, refs);
        _collectRefsFromType(type.valueType, refs);
      case OptionType():
        _collectRefsFromType(type.innerType, refs);
      case ProductType():
        for (final elem in type.elements) {
          _collectRefsFromType(elem.type, refs);
        }
      case SumType():
        for (final variant in type.variants) {
          _collectRefsFromType(variant.algebraicType, refs);
        }
      default:
        break;
    }
  }

  /// Tries to find a meaningful name for the typespace entry at [refIndex]
  /// by scanning table fields and reducer params that reference it.
  String? _findNameForRef(int refIndex) {
    // Check table fields.
    for (final table in schema.tables) {
      final type = schema.typespace[table.productTypeRef].type;
      if (type is ProductType) {
        for (final elem in type.elements) {
          if (elem.type is RefType && (elem.type as RefType).ref == refIndex) {
            return elem.name;
          }
        }
      }
    }
    // Check reducer params.
    for (final reducer in schema.reducers) {
      for (final param in reducer.params) {
        if (param.type is RefType && (param.type as RefType).ref == refIndex) {
          return param.name;
        }
      }
    }
    return null;
  }

  // ---------------------------------------------------------------------------
  // Dart type mapping
  // ---------------------------------------------------------------------------

  /// Maps an [AlgebraicType] to a Dart type string.
  String dartType(AlgebraicType type) {
    switch (type) {
      case BoolType():
        return 'bool';
      case U8Type():
        return 'int';
      case U16Type():
        return 'int';
      case U32Type():
        return 'int';
      case U64Type():
        return 'int';
      case U128AlgType():
        return 'U128';
      case U256AlgType():
        return 'U256';
      case I8Type():
        return 'int';
      case I16Type():
        return 'int';
      case I32Type():
        return 'int';
      case I64Type():
        return 'int';
      case I128AlgType():
        return 'I128';
      case I256AlgType():
        return 'I256';
      case F32Type():
        return 'double';
      case F64Type():
        return 'double';
      case StringType():
        return 'String';
      case ArrayType():
        return 'List<${dartType(type.elementType)}>';
      case MapType():
        return 'Map<${dartType(type.keyType)}, ${dartType(type.valueType)}>';
      case OptionType():
        return '${dartType(type.innerType)}?';
      case IdentityType():
        return 'Identity';
      case ConnectionIdType():
        return 'ConnectionId';
      case TimestampType():
        return 'Timestamp';
      case ProductType():
        return 'dynamic';
      case SumType():
        return 'dynamic';
      case RefType():
        final resolved = schema.resolveType(type);
        // If the ref has a name in our map, use it.
        if (_typeNames.containsKey(type.ref)) {
          return _typeNames[type.ref]!;
        }
        // Otherwise, resolve to the underlying dart type.
        return dartType(resolved);
    }
  }

  // ---------------------------------------------------------------------------
  // BSATN encode expression generation
  // ---------------------------------------------------------------------------

  /// Generates a Dart expression (or statement block) that encodes [varName]
  /// of the given [type] using a BsatnEncoder named `encoder`.
  String encodeExpr(AlgebraicType type, String varName, {int indent = 4}) {
    final pad = ' ' * indent;
    switch (type) {
      case BoolType():
        return '${pad}encoder.writeBool($varName);';
      case U8Type():
        return '${pad}encoder.writeU8($varName);';
      case U16Type():
        return '${pad}encoder.writeU16($varName);';
      case U32Type():
        return '${pad}encoder.writeU32($varName);';
      case U64Type():
        return '${pad}encoder.writeU64($varName);';
      case U128AlgType():
        return '${pad}encoder.writeU128($varName);';
      case U256AlgType():
        return '${pad}encoder.writeU256($varName);';
      case I8Type():
        return '${pad}encoder.writeI8($varName);';
      case I16Type():
        return '${pad}encoder.writeI16($varName);';
      case I32Type():
        return '${pad}encoder.writeI32($varName);';
      case I64Type():
        return '${pad}encoder.writeI64($varName);';
      case I128AlgType():
        return '${pad}encoder.writeI128($varName);';
      case I256AlgType():
        return '${pad}encoder.writeI256($varName);';
      case F32Type():
        return '${pad}encoder.writeF32($varName);';
      case F64Type():
        return '${pad}encoder.writeF64($varName);';
      case StringType():
        return '${pad}encoder.writeString($varName);';
      case IdentityType():
        return '$pad$varName.writeBsatn(encoder);';
      case ConnectionIdType():
        return '$pad$varName.writeBsatn(encoder);';
      case TimestampType():
        return '$pad$varName.writeBsatn(encoder);';
      case ArrayType():
        final elemEncode =
            encodeExpr(type.elementType, 'item', indent: indent + 2);
        return '${pad}encoder.writeArrayHeader($varName.length);\n'
            '${pad}for (final item in $varName) {\n'
            '$elemEncode\n'
            '$pad}';
      case MapType():
        final keyEncode =
            encodeExpr(type.keyType, 'entry.key', indent: indent + 2);
        final valueEncode =
            encodeExpr(type.valueType, 'entry.value', indent: indent + 2);
        return '${pad}encoder.writeArrayHeader($varName.length);\n'
            '${pad}for (final entry in $varName.entries) {\n'
            '$keyEncode\n'
            '$valueEncode\n'
            '$pad}';
      case OptionType():
        final innerEncode = encodeExpr(type.innerType, varName,
            indent: indent + 2);
        return '${pad}if ($varName != null) {\n'
            '$pad  encoder.writeOptionSome();\n'
            '$innerEncode\n'
            '$pad} else {\n'
            '$pad  encoder.writeOptionNone();\n'
            '$pad}';
      case RefType():
        final resolved = schema.resolveType(type);
        if (_typeNames.containsKey(type.ref)) {
          // Named type: call its writeBsatn method.
          return '$pad$varName.writeBsatn(encoder);';
        }
        return encodeExpr(resolved, varName, indent: indent);
      case ProductType():
        // Inline product: encode each field.
        final buf = StringBuffer();
        for (final elem in type.elements) {
          final fieldName = _toCamelCase(elem.name ?? '');
          buf.writeln(encodeExpr(elem.type, '$varName.$fieldName',
              indent: indent));
        }
        return buf.toString().trimRight();
      case SumType():
        // Tagged union: dispatch on type.
        return '$pad$varName.writeBsatn(encoder);';
    }
  }

  // ---------------------------------------------------------------------------
  // BSATN decode expression generation
  // ---------------------------------------------------------------------------

  /// Generates a Dart expression that decodes a value of [type] from a
  /// BsatnDecoder named `decoder`.
  String decodeExpr(AlgebraicType type) {
    switch (type) {
      case BoolType():
        return 'decoder.readBool()';
      case U8Type():
        return 'decoder.readU8()';
      case U16Type():
        return 'decoder.readU16()';
      case U32Type():
        return 'decoder.readU32()';
      case U64Type():
        return 'decoder.readU64()';
      case U128AlgType():
        return 'decoder.readU128()';
      case U256AlgType():
        return 'decoder.readU256()';
      case I8Type():
        return 'decoder.readI8()';
      case I16Type():
        return 'decoder.readI16()';
      case I32Type():
        return 'decoder.readI32()';
      case I64Type():
        return 'decoder.readI64()';
      case I128AlgType():
        return 'decoder.readI128()';
      case I256AlgType():
        return 'decoder.readI256()';
      case F32Type():
        return 'decoder.readF32()';
      case F64Type():
        return 'decoder.readF64()';
      case StringType():
        return 'decoder.readString()';
      case IdentityType():
        return 'Identity.readBsatn(decoder)';
      case ConnectionIdType():
        return 'ConnectionId.readBsatn(decoder)';
      case TimestampType():
        return 'Timestamp.readBsatn(decoder)';
      case ArrayType():
        final elemDecode = decodeExpr(type.elementType);
        return '[for (var i = 0; i < decoder.readArrayHeader(); i++) $elemDecode]';
      case MapType():
        final keyDecode = decodeExpr(type.keyType);
        final valueDecode = decodeExpr(type.valueType);
        return '{ for (var i = 0; i < decoder.readArrayHeader(); i++) $keyDecode: $valueDecode }';
      case OptionType():
        final innerDecode = decodeExpr(type.innerType);
        return 'decoder.readOption() ? $innerDecode : null';
      case RefType():
        if (_typeNames.containsKey(type.ref)) {
          return '${_typeNames[type.ref]!}.readBsatn(decoder)';
        }
        final resolved = schema.resolveType(type);
        return decodeExpr(resolved);
      case ProductType():
        return 'dynamic /* inline product */';
      case SumType():
        return 'dynamic /* inline sum */';
    }
  }

  // ---------------------------------------------------------------------------
  // Table type code generation
  // ---------------------------------------------------------------------------

  /// Generates the Dart class for a table's row type.
  String _generateTableTypeCode(TableDef table) {
    final className = _toPascalCase(table.name);
    final type = schema.typespace[table.productTypeRef].type;

    if (type is! ProductType) {
      throw StateError(
          'Table ${table.name} references typespace entry '
          '${table.productTypeRef} which is not a ProductType');
    }

    final fields = type.elements;
    final buf = StringBuffer();
    buf.writeln(_generatedHeader);
    buf.writeln("import 'package:spacetimedb_sdk/spacetimedb.dart';");
    buf.writeln();

    // Add imports for custom types referenced by this table.
    final imports = _collectTypeImports(type);
    for (final imp in imports) {
      buf.writeln(imp);
    }
    if (imports.isNotEmpty) buf.writeln();

    buf.writeln('class $className {');

    // Fields.
    for (final field in fields) {
      final fieldName = _toCamelCase(field.name ?? 'field${fields.indexOf(field)}');
      final fieldType = dartType(field.type);
      buf.writeln('  final $fieldType $fieldName;');
    }
    buf.writeln();

    // Constructor.
    buf.writeln('  $className({');
    for (final field in fields) {
      final fieldName = _toCamelCase(field.name ?? 'field${fields.indexOf(field)}');
      final isNullable = field.type is OptionType;
      if (isNullable) {
        buf.writeln('    this.$fieldName,');
      } else {
        buf.writeln('    required this.$fieldName,');
      }
    }
    buf.writeln('  });');
    buf.writeln();

    // writeBsatn method.
    buf.writeln('  void writeBsatn(BsatnEncoder encoder) {');
    for (final field in fields) {
      final fieldName = _toCamelCase(field.name ?? 'field${fields.indexOf(field)}');
      buf.writeln(encodeExpr(field.type, fieldName, indent: 4));
    }
    buf.writeln('  }');
    buf.writeln();

    // readBsatn static method.
    buf.writeln('  static $className readBsatn(BsatnDecoder decoder) {');
    buf.writeln('    return $className(');
    for (final field in fields) {
      final fieldName = _toCamelCase(field.name ?? 'field${fields.indexOf(field)}');
      buf.writeln('      $fieldName: ${decodeExpr(field.type)},');
    }
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();

    // Equality operator.
    if (table.primaryKey != null && table.primaryKey! < fields.length) {
      final pkField = _toCamelCase(
          fields[table.primaryKey!].name ?? 'field${table.primaryKey}');
      buf.writeln('  @override');
      buf.writeln('  bool operator ==(Object other) =>');
      buf.writeln(
          '      other is $className && $pkField == other.$pkField;');
      buf.writeln();
      buf.writeln('  @override');
      buf.writeln('  int get hashCode => $pkField.hashCode;');
    } else {
      // Fall back to all-fields equality.
      buf.writeln('  @override');
      buf.writeln('  bool operator ==(Object other) =>');
      buf.write('      other is $className');
      for (final field in fields) {
        final fieldName =
            _toCamelCase(field.name ?? 'field${fields.indexOf(field)}');
        buf.write(' &&\n      $fieldName == other.$fieldName');
      }
      buf.writeln(';');
      buf.writeln();
      buf.writeln('  @override');
      if (fields.isEmpty) {
        buf.writeln('  int get hashCode => 0;');
      } else {
        final hashFields = fields
            .map((f) =>
                _toCamelCase(f.name ?? 'field${fields.indexOf(f)}'))
            .toList();
        if (hashFields.length == 1) {
          buf.writeln('  int get hashCode => ${hashFields.first}.hashCode;');
        } else {
          buf.writeln(
              '  int get hashCode => Object.hash(${hashFields.join(', ')});');
        }
      }
    }
    buf.writeln();

    // toString.
    buf.writeln('  @override');
    if (fields.isEmpty) {
      buf.writeln("  String toString() => '$className()';");
    } else {
      final firstTwoFields = fields.take(3).map((f) {
        final name = _toCamelCase(f.name ?? 'field${fields.indexOf(f)}');
        return '$name: \$$name';
      }).join(', ');
      buf.writeln("  String toString() => '$className($firstTwoFields)';");
    }
    buf.writeln('}');

    return buf.toString();
  }

  // ---------------------------------------------------------------------------
  // Custom type generation (enums, tagged unions, standalone structs)
  // ---------------------------------------------------------------------------

  /// Generates files for custom types that are not table row types.
  Future<void> _generateCustomTypeFiles(Directory typesDir) async {
    // Generate simple enums.
    for (final refIdx in _enumTypeRefs) {
      final type = schema.typespace[refIdx].type as SumType;
      final name = _typeNames[refIdx]!;
      final code = _generateEnumCode(name, type);
      final fileName = _toSnakeCase(name);
      await File('${typesDir.path}/$fileName.dart').writeAsString(code);
    }

    // Generate tagged unions.
    for (final refIdx in _taggedUnionTypeRefs) {
      final type = schema.typespace[refIdx].type as SumType;
      final name = _typeNames[refIdx]!;
      final code = _generateTaggedUnionCode(name, type);
      final fileName = _toSnakeCase(name);
      await File('${typesDir.path}/$fileName.dart').writeAsString(code);
    }

    // Generate custom product types (standalone structs).
    for (final refIdx in _customProductTypeRefs) {
      final type = schema.typespace[refIdx].type as ProductType;
      final name = _typeNames[refIdx]!;
      final code = generateCustomProductCode(name, type);
      final fileName = _toSnakeCase(name);
      await File('${typesDir.path}/$fileName.dart').writeAsString(code);
    }
  }

  /// Generates code for a simple enum (all variants have empty payloads).
  String _generateEnumCode(String name, SumType type) {
    final buf = StringBuffer();
    buf.writeln(_generatedHeader);
    buf.writeln("import 'package:spacetimedb_sdk/spacetimedb.dart';");
    buf.writeln();
    buf.writeln('enum $name {');
    for (var i = 0; i < type.variants.length; i++) {
      final variant = type.variants[i];
      final variantName = _toCamelCase(variant.name ?? 'variant$i');
      final isLast = i == type.variants.length - 1;
      buf.writeln('  $variantName($i)${isLast ? ';' : ','}');
    }
    buf.writeln();
    buf.writeln('  final int tag;');
    buf.writeln('  const $name(this.tag);');
    buf.writeln();
    buf.writeln('  void writeBsatn(BsatnEncoder encoder) {');
    buf.writeln('    encoder.writeSumTag(tag);');
    buf.writeln('  }');
    buf.writeln();
    buf.writeln('  static $name readBsatn(BsatnDecoder decoder) {');
    buf.writeln('    final tag = decoder.readSumTag();');
    buf.writeln('    return $name.values.firstWhere(');
    buf.writeln('      (v) => v.tag == tag,');
    buf.writeln(
        "      orElse: () => throw BsatnDecodeException('Unknown $name tag: \$tag'),");
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln('}');
    return buf.toString();
  }

  /// Generates code for a tagged union (sealed class with variant subclasses).
  String _generateTaggedUnionCode(String name, SumType type) {
    final buf = StringBuffer();
    buf.writeln(_generatedHeader);
    buf.writeln("import 'package:spacetimedb_sdk/spacetimedb.dart';");
    buf.writeln();

    // Collect imports for types referenced by variants.
    final imports = <String>{};
    for (final variant in type.variants) {
      _collectImportsFromType(variant.algebraicType, imports);
    }
    for (final imp in imports) {
      buf.writeln(imp);
    }
    if (imports.isNotEmpty) buf.writeln();

    buf.writeln('sealed class $name {');
    buf.writeln('  const $name();');
    buf.writeln();
    buf.writeln('  void writeBsatn(BsatnEncoder encoder);');
    buf.writeln();
    buf.writeln('  static $name readBsatn(BsatnDecoder decoder) {');
    buf.writeln('    final tag = decoder.readSumTag();');
    buf.writeln('    switch (tag) {');
    for (var i = 0; i < type.variants.length; i++) {
      final variant = type.variants[i];
      final variantClassName =
          '$name${_toPascalCase(variant.name ?? 'Variant$i')}';
      final variantType = variant.algebraicType;
      buf.writeln('      case $i:');
      if (variantType is ProductType && variantType.elements.isEmpty) {
        buf.writeln('        return const $variantClassName();');
      } else {
        buf.writeln(
            '        return $variantClassName._readPayload(decoder);');
      }
    }
    buf.writeln('      default:');
    buf.writeln(
        "        throw BsatnDecodeException('Unknown $name tag: \$tag');");
    buf.writeln('    }');
    buf.writeln('  }');
    buf.writeln('}');
    buf.writeln();

    // Generate subclasses for each variant.
    for (var i = 0; i < type.variants.length; i++) {
      final variant = type.variants[i];
      final variantClassName =
          '$name${_toPascalCase(variant.name ?? 'Variant$i')}';
      final variantType = variant.algebraicType;

      buf.writeln('class $variantClassName extends $name {');

      if (variantType is ProductType && variantType.elements.isEmpty) {
        // Empty variant.
        buf.writeln('  const $variantClassName();');
        buf.writeln();
        buf.writeln('  @override');
        buf.writeln('  void writeBsatn(BsatnEncoder encoder) {');
        buf.writeln('    encoder.writeSumTag($i);');
        buf.writeln('  }');
      } else if (variantType is ProductType) {
        // Variant with fields.
        for (final field in variantType.elements) {
          final fieldName = _toCamelCase(
              field.name ?? 'field${variantType.elements.indexOf(field)}');
          final fieldType = dartType(field.type);
          buf.writeln('  final $fieldType $fieldName;');
        }
        buf.writeln();
        buf.writeln('  const $variantClassName({');
        for (final field in variantType.elements) {
          final fieldName = _toCamelCase(
              field.name ?? 'field${variantType.elements.indexOf(field)}');
          final isNullable = field.type is OptionType;
          if (isNullable) {
            buf.writeln('    this.$fieldName,');
          } else {
            buf.writeln('    required this.$fieldName,');
          }
        }
        buf.writeln('  });');
        buf.writeln();
        buf.writeln(
            '  static $variantClassName _readPayload(BsatnDecoder decoder) {');
        buf.writeln('    return $variantClassName(');
        for (final field in variantType.elements) {
          final fieldName = _toCamelCase(
              field.name ?? 'field${variantType.elements.indexOf(field)}');
          buf.writeln('      $fieldName: ${decodeExpr(field.type)},');
        }
        buf.writeln('    );');
        buf.writeln('  }');
        buf.writeln();
        buf.writeln('  @override');
        buf.writeln('  void writeBsatn(BsatnEncoder encoder) {');
        buf.writeln('    encoder.writeSumTag($i);');
        for (final field in variantType.elements) {
          final fieldName = _toCamelCase(
              field.name ?? 'field${variantType.elements.indexOf(field)}');
          buf.writeln(encodeExpr(field.type, fieldName, indent: 4));
        }
        buf.writeln('  }');
      } else {
        // Single non-product payload.
        final payloadType = dartType(variantType);
        buf.writeln('  final $payloadType value;');
        buf.writeln();
        buf.writeln('  const $variantClassName(this.value);');
        buf.writeln();
        buf.writeln(
            '  static $variantClassName _readPayload(BsatnDecoder decoder) {');
        buf.writeln(
            '    return $variantClassName(${decodeExpr(variantType)});');
        buf.writeln('  }');
        buf.writeln();
        buf.writeln('  @override');
        buf.writeln('  void writeBsatn(BsatnEncoder encoder) {');
        buf.writeln('    encoder.writeSumTag($i);');
        buf.writeln(encodeExpr(variantType, 'value', indent: 4));
        buf.writeln('  }');
      }
      buf.writeln('}');
      if (i < type.variants.length - 1) buf.writeln();
    }

    return buf.toString();
  }

  /// Generates code for a standalone product type (struct not used as a table).
  @visibleForTesting
  String generateCustomProductCode(String name, ProductType type) {
    final buf = StringBuffer();
    buf.writeln(_generatedHeader);
    buf.writeln("import 'package:spacetimedb_sdk/spacetimedb.dart';");
    buf.writeln();

    final imports = _collectTypeImports(type);
    for (final imp in imports) {
      buf.writeln(imp);
    }
    if (imports.isNotEmpty) buf.writeln();

    buf.writeln('class $name {');

    for (final field in type.elements) {
      final fieldName =
          _toCamelCase(field.name ?? 'field${type.elements.indexOf(field)}');
      final fieldType = dartType(field.type);
      buf.writeln('  final $fieldType $fieldName;');
    }
    buf.writeln();

    buf.writeln('  $name({');
    for (final field in type.elements) {
      final fieldName =
          _toCamelCase(field.name ?? 'field${type.elements.indexOf(field)}');
      final isNullable = field.type is OptionType;
      if (isNullable) {
        buf.writeln('    this.$fieldName,');
      } else {
        buf.writeln('    required this.$fieldName,');
      }
    }
    buf.writeln('  });');
    buf.writeln();

    buf.writeln('  void writeBsatn(BsatnEncoder encoder) {');
    for (final field in type.elements) {
      final fieldName =
          _toCamelCase(field.name ?? 'field${type.elements.indexOf(field)}');
      buf.writeln(encodeExpr(field.type, fieldName, indent: 4));
    }
    buf.writeln('  }');
    buf.writeln();

    buf.writeln('  static $name readBsatn(BsatnDecoder decoder) {');
    buf.writeln('    return $name(');
    for (final field in type.elements) {
      final fieldName =
          _toCamelCase(field.name ?? 'field${type.elements.indexOf(field)}');
      buf.writeln('      $fieldName: ${decodeExpr(field.type)},');
    }
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();

    buf.writeln('  @override');
    buf.writeln('  bool operator ==(Object other) =>');
    buf.write('      other is $name');
    for (final field in type.elements) {
      final fieldName =
          _toCamelCase(field.name ?? 'field${type.elements.indexOf(field)}');
      buf.write(' &&\n      $fieldName == other.$fieldName');
    }
    buf.writeln(';');
    buf.writeln();
    buf.writeln('  @override');
    if (type.elements.isEmpty) {
      buf.writeln('  int get hashCode => 0;');
    } else {
      final hashFields = type.elements
          .map((f) =>
              _toCamelCase(f.name ?? 'field${type.elements.indexOf(f)}'))
          .toList();
      if (hashFields.length == 1) {
        buf.writeln('  int get hashCode => ${hashFields.first}.hashCode;');
      } else {
        buf.writeln(
            '  int get hashCode => Object.hash(${hashFields.join(', ')});');
      }
    }
    buf.writeln();

    buf.writeln('  @override');
    if (type.elements.isEmpty) {
      buf.writeln("  String toString() => '$name()';");
    } else {
      final firstFields = type.elements.take(3).map((f) {
        final n = _toCamelCase(f.name ?? 'field${type.elements.indexOf(f)}');
        return '$n: \$$n';
      }).join(', ');
      buf.writeln("  String toString() => '$name($firstFields)';");
    }
    buf.writeln('}');

    return buf.toString();
  }

  // ---------------------------------------------------------------------------
  // Table handle generation
  // ---------------------------------------------------------------------------

  /// Generates a table handle class for the given table.
  String _generateTableHandleCode(TableDef table) {
    final className = _toPascalCase(table.name);
    final handleName = '${className}TableHandle';
    final type = schema.typespace[table.productTypeRef].type as ProductType;
    final fields = type.elements;
    final tableSnake = _toSnakeCase(table.name);

    final buf = StringBuffer();
    buf.writeln(_generatedHeader);
    buf.writeln("import 'package:spacetimedb_sdk/spacetimedb.dart';");
    buf.writeln();
    buf.writeln("import '../types/$tableSnake.dart';");

    // Import custom types used by this table.
    final customImports = _collectCustomTypeImportsForType(type);
    for (final imp in customImports) {
      buf.writeln(imp);
    }
    buf.writeln();

    // Determine PK extractor type and expression.
    String? pkType;
    String? pkFieldName;
    if (table.primaryKey != null && table.primaryKey! < fields.length) {
      final pkField = fields[table.primaryKey!];
      pkFieldName = _toCamelCase(pkField.name ?? 'field${table.primaryKey}');
      pkType = dartType(pkField.type);
    }

    buf.writeln('class $handleName {');
    buf.writeln('  final TableCache<$className> _cache;');
    buf.writeln();
    buf.writeln('  $handleName(this._cache);');
    buf.writeln();

    // Factory that creates and registers the cache.
    buf.writeln('  /// Creates a [$handleName] backed by a [TableCache]');
    buf.writeln(
        '  /// configured for the "${table.name}" table.');
    buf.writeln('  static TableCache<$className> createCache() {');
    buf.writeln('    return TableCache<$className>(');
    buf.writeln("      tableName: '${table.name}',");
    buf.writeln('      decoder: $className.readBsatn,');
    if (pkFieldName != null) {
      buf.writeln('      pkExtractor: (row) => row.$pkFieldName,');
    }
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();

    buf.writeln('  /// All currently cached rows.');
    buf.writeln('  Iterable<$className> get rows => _cache.rows;');
    buf.writeln();
    buf.writeln('  /// The number of cached rows.');
    buf.writeln('  int get count => _cache.count;');
    buf.writeln();

    // Typed PK finder.
    if (pkFieldName != null && pkType != null) {
      final methodName =
          'findBy${pkFieldName[0].toUpperCase()}${pkFieldName.substring(1)}';
      buf.writeln(
          '  /// Finds a row by its primary key [$pkFieldName].');
      buf.writeln(
          '  $className? $methodName($pkType $pkFieldName) =>');
      buf.writeln('      _cache.findByPk($pkFieldName);');
      buf.writeln();
    }

    buf.writeln(
        '  /// Returns all rows matching the given [test] predicate.');
    buf.writeln(
        '  Iterable<$className> where(bool Function($className) test) =>');
    buf.writeln('      _cache.where(test);');
    buf.writeln();

    buf.writeln(
        '  /// Registers a callback invoked when a row is inserted.');
    buf.writeln(
        '  void onInsert(void Function($className) callback) =>');
    buf.writeln('      _cache.onInsert(callback);');
    buf.writeln();
    buf.writeln(
        '  /// Registers a callback invoked when a row is updated.');
    buf.writeln(
        '  void onUpdate(void Function($className, $className) callback) =>');
    buf.writeln('      _cache.onUpdate(callback);');
    buf.writeln();
    buf.writeln(
        '  /// Registers a callback invoked when a row is deleted.');
    buf.writeln(
        '  void onDelete(void Function($className) callback) =>');
    buf.writeln('      _cache.onDelete(callback);');
    buf.writeln();

    buf.writeln(
        '  /// Removes a previously registered insert callback.');
    buf.writeln(
        '  void removeOnInsert(void Function($className) callback) =>');
    buf.writeln('      _cache.removeOnInsert(callback);');
    buf.writeln();
    buf.writeln(
        '  /// Removes a previously registered update callback.');
    buf.writeln(
        '  void removeOnUpdate(void Function($className, $className) callback) =>');
    buf.writeln('      _cache.removeOnUpdate(callback);');
    buf.writeln();
    buf.writeln(
        '  /// Removes a previously registered delete callback.');
    buf.writeln(
        '  void removeOnDelete(void Function($className) callback) =>');
    buf.writeln('      _cache.removeOnDelete(callback);');
    buf.writeln('}');

    return buf.toString();
  }

  // ---------------------------------------------------------------------------
  // Reducers generation
  // ---------------------------------------------------------------------------

  /// Generates the RemoteReducers class containing call methods and callback
  /// registrations for all non-lifecycle reducers.
  String _generateReducersCode() {
    final nonLifecycleReducers =
        schema.reducers.where((r) => !r.isLifecycle).toList();

    final buf = StringBuffer();
    buf.writeln(_generatedHeader);
    buf.writeln("import 'dart:typed_data';");
    buf.writeln();
    buf.writeln("import 'package:spacetimedb_sdk/spacetimedb.dart';");
    buf.writeln();

    // Import custom types used by reducer params.
    // Reducers file lives in the root output dir, not in types/.
    final imports = <String>{};
    for (final reducer in nonLifecycleReducers) {
      for (final param in reducer.params) {
        _collectImportsFromType(param.type, imports, fromTypesDir: false);
      }
    }
    for (final imp in imports) {
      buf.writeln(imp);
    }
    if (imports.isNotEmpty) buf.writeln();

    // Callback type alias for readability.
    buf.writeln(
        '/// Callback type for reducer completion events.');
    buf.writeln(
        'typedef ReducerCallback = void Function(ReducerCallbackEvent event);');
    buf.writeln();

    buf.writeln('/// Provides typed methods for calling reducers and');
    buf.writeln('/// registering callbacks for reducer completion events.');
    buf.writeln('class RemoteReducers {');
    buf.writeln(
        '  final Future<void> Function(String reducer, Uint8List args) _callReducer;');
    buf.writeln(
        '  final void Function(String reducer, ReducerCallback callback) _onReducer;');
    buf.writeln();
    buf.writeln('  RemoteReducers({');
    buf.writeln(
        '    required Future<void> Function(String reducer, Uint8List args) callReducer,');
    buf.writeln(
        '    required void Function(String reducer, ReducerCallback callback) onReducer,');
    buf.writeln('  })  : _callReducer = callReducer,');
    buf.writeln('        _onReducer = onReducer;');
    buf.writeln();

    for (final reducer in nonLifecycleReducers) {
      final methodName = _toCamelCase(reducer.name);
      final callbackMethodName =
          'on${methodName[0].toUpperCase()}${methodName.substring(1)}';

      // Build parameter list.
      final params = <String>[];
      for (final param in reducer.params) {
        final paramName =
            _toCamelCase(param.name ?? 'arg${reducer.params.indexOf(param)}');
        final paramType = dartType(param.type);
        params.add('$paramType $paramName');
      }
      final paramList = params.join(', ');

      // Call method.
      buf.writeln('  /// Calls the `${reducer.name}` reducer.');
      buf.writeln('  Future<void> $methodName($paramList) {');
      buf.writeln('    final encoder = BsatnEncoder();');
      for (final param in reducer.params) {
        final paramName =
            _toCamelCase(param.name ?? 'arg${reducer.params.indexOf(param)}');
        buf.writeln(encodeExpr(param.type, paramName, indent: 4));
      }
      buf.writeln(
          "    return _callReducer('${reducer.name}', encoder.toBytes());");
      buf.writeln('  }');
      buf.writeln();

      // Callback registration.
      buf.writeln(
          '  /// Registers a callback for when `${reducer.name}` completes.');
      buf.writeln('  void $callbackMethodName(ReducerCallback callback) {');
      buf.writeln("    _onReducer('${reducer.name}', callback);");
      buf.writeln('  }');
      buf.writeln();
    }

    buf.writeln('}');

    return buf.toString();
  }

  // ---------------------------------------------------------------------------
  // Barrel export generation
  // ---------------------------------------------------------------------------

  /// Generates the barrel export file that re-exports all generated types,
  /// table handles, and reducers.
  String _generateBarrelCode() {
    final buf = StringBuffer();
    buf.writeln(_generatedHeader);
    buf.writeln();

    // Export table types.
    buf.writeln('// Table row types');
    for (final table in schema.tables) {
      final fileName = _toSnakeCase(table.name);
      buf.writeln("export 'types/$fileName.dart';");
    }
    buf.writeln();

    // Export custom types.
    final allCustomRefs = [
      ..._enumTypeRefs,
      ..._taggedUnionTypeRefs,
      ..._customProductTypeRefs,
    ];
    if (allCustomRefs.isNotEmpty) {
      buf.writeln('// Custom types');
      for (final refIdx in allCustomRefs) {
        final name = _typeNames[refIdx]!;
        final fileName = _toSnakeCase(name);
        buf.writeln("export 'types/$fileName.dart';");
      }
      buf.writeln();
    }

    // Export table handles.
    buf.writeln('// Table handles');
    for (final table in schema.tables) {
      final fileName = _toSnakeCase(table.name);
      buf.writeln("export 'tables/${fileName}_table.dart';");
    }
    buf.writeln();

    // Export reducers.
    buf.writeln('// Reducers');
    buf.writeln("export 'reducers.dart';");

    return buf.toString();
  }

  // ---------------------------------------------------------------------------
  // Import collection helpers
  // ---------------------------------------------------------------------------

  /// Collects relative import statements for custom types referenced by a
  /// product type's fields. [fromTypesDir] controls the import prefix:
  /// when true, uses peer imports (for files inside types/); when false,
  /// uses `types/` prefix (for files in the root output dir like reducers).
  Set<String> _collectTypeImports(ProductType type, {bool fromTypesDir = true}) {
    final imports = <String>{};
    for (final field in type.elements) {
      _collectImportsFromType(field.type, imports, fromTypesDir: fromTypesDir);
    }
    return imports;
  }

  /// Recursively collects import statements for named custom types referenced
  /// by [type].
  void _collectImportsFromType(AlgebraicType type, Set<String> imports, {bool fromTypesDir = true}) {
    switch (type) {
      case RefType():
        if (_enumTypeRefs.contains(type.ref) ||
            _taggedUnionTypeRefs.contains(type.ref) ||
            _customProductTypeRefs.contains(type.ref)) {
          final name = _typeNames[type.ref]!;
          final fileName = _toSnakeCase(name);
          final prefix = fromTypesDir ? '' : 'types/';
          imports.add("import '$prefix$fileName.dart';");
        }
        // Also recurse into the referenced type.
        if (type.ref >= 0 && type.ref < schema.typespace.length) {
          _collectImportsFromType(schema.typespace[type.ref].type, imports, fromTypesDir: fromTypesDir);
        }
      case ArrayType():
        _collectImportsFromType(type.elementType, imports, fromTypesDir: fromTypesDir);
      case MapType():
        _collectImportsFromType(type.keyType, imports, fromTypesDir: fromTypesDir);
        _collectImportsFromType(type.valueType, imports, fromTypesDir: fromTypesDir);
      case OptionType():
        _collectImportsFromType(type.innerType, imports, fromTypesDir: fromTypesDir);
      case ProductType():
        for (final elem in type.elements) {
          _collectImportsFromType(elem.type, imports, fromTypesDir: fromTypesDir);
        }
      case SumType():
        for (final variant in type.variants) {
          _collectImportsFromType(variant.algebraicType, imports, fromTypesDir: fromTypesDir);
        }
      default:
        break;
    }
  }

  /// Collects imports for custom types used by a table type, formatted as
  /// relative imports from the tables directory.
  Set<String> _collectCustomTypeImportsForType(ProductType type) {
    final imports = <String>{};
    for (final field in type.elements) {
      _collectCustomTableImportsFromType(field.type, imports);
    }
    return imports;
  }

  void _collectCustomTableImportsFromType(
      AlgebraicType type, Set<String> imports) {
    switch (type) {
      case RefType():
        if (_enumTypeRefs.contains(type.ref) ||
            _taggedUnionTypeRefs.contains(type.ref) ||
            _customProductTypeRefs.contains(type.ref)) {
          final name = _typeNames[type.ref]!;
          final fileName = _toSnakeCase(name);
          imports.add("import '../types/$fileName.dart';");
        }
        if (type.ref >= 0 && type.ref < schema.typespace.length) {
          _collectCustomTableImportsFromType(
              schema.typespace[type.ref].type, imports);
        }
      case ArrayType():
        _collectCustomTableImportsFromType(type.elementType, imports);
      case MapType():
        _collectCustomTableImportsFromType(type.keyType, imports);
        _collectCustomTableImportsFromType(type.valueType, imports);
      case OptionType():
        _collectCustomTableImportsFromType(type.innerType, imports);
      case ProductType():
        for (final elem in type.elements) {
          _collectCustomTableImportsFromType(elem.type, imports);
        }
      case SumType():
        for (final variant in type.variants) {
          _collectCustomTableImportsFromType(variant.algebraicType, imports);
        }
      default:
        break;
    }
  }
}

// =============================================================================
// Naming convention utilities
// =============================================================================

/// Converts a snake_case or PascalCase string to PascalCase.
String _toPascalCase(String input) {
  if (input.isEmpty) return input;

  // Handle already-PascalCase strings.
  if (!input.contains('_') && input[0] == input[0].toUpperCase()) {
    return input;
  }

  return input.split('_').map((part) {
    if (part.isEmpty) return '';
    return part[0].toUpperCase() + part.substring(1).toLowerCase();
  }).join();
}

/// Converts a snake_case or PascalCase string to camelCase.
String _toCamelCase(String input) {
  if (input.isEmpty) return input;

  final pascal = _toPascalCase(input);
  if (pascal.isEmpty) return pascal;
  return pascal[0].toLowerCase() + pascal.substring(1);
}

/// Converts a PascalCase or camelCase string to snake_case.
String _toSnakeCase(String input) {
  if (input.isEmpty) return input;

  // If already snake_case, just return lowercased.
  if (input.contains('_')) return input.toLowerCase();

  final buf = StringBuffer();
  for (var i = 0; i < input.length; i++) {
    final char = input[i];
    if (char == char.toUpperCase() && char != char.toLowerCase()) {
      if (i > 0) buf.write('_');
      buf.write(char.toLowerCase());
    } else {
      buf.write(char);
    }
  }
  return buf.toString();
}
